/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.81
 * Generated at: 2022-07-20 11:22:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.common.util.PageInfo;
import com.kh.mvc.board.model.vo.Board;
import java.util.List;
import com.kh.mvc.member.model.vo.Member;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/common/header.jsp", Long.valueOf(1658217562000L));
    _jspx_dependants.put("/views/common/footer.jsp", Long.valueOf(1658213228000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.mvc.member.model.vo.Member");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.kh.mvc.board.model.vo.Board");
    _jspx_imports_classes.add("com.kh.common.util.PageInfo");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String saveId = "";
	Member loginMember = (Member)session.getAttribute("loginMember");
	Cookie[] cookies = request.getCookies();
	
	if(cookies != null){
		for(Cookie c : cookies) { 
			if(c.getName().equals("saveId")){
				saveId = c.getValue();
				break;
			}
		}
	}

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!-- 헤더부 구현 할 기능 리스트 -->\r\n");
      out.write("<!-- 1. 로그인 공통부 기능 구현 -->\r\n");
      out.write("<!-- 2. 메뉴(네비게이션) 기능 작성 -->\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>KH 게시판</title>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/resources/css/main.css\">\r\n");
      out.write("	<script src=\"");
      out.print(path);
      out.write("/resources/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("	<h2>Hello MVC2 - Board!</h2>\r\n");
      out.write("	<div class=\"login-container\">\r\n");
      out.write("		");
if(loginMember == null){ 
      out.write("\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("			<form id=\"loginFrm\" action=\"");
      out.print(path);
      out.write("/login\" method=\"post\">\r\n");
      out.write("				<table>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>\r\n");
      out.write("							<input type=\"text\" name=\"userId\" id=\"userId\" value=\"");
      out.print(saveId );
      out.write("\" placeholder=\"아이디\" required/>\r\n");
      out.write("						</td>\r\n");
      out.write("						<td></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>\r\n");
      out.write("							<input type=\"password\" name=\"userPwd\" id=\"userPwd\" placeholder=\"비밀번호\" required/>\r\n");
      out.write("						</td>\r\n");
      out.write("						<td>\r\n");
      out.write("							<input type=\"submit\" value=\"로그인\">\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td colspan=\"2\">\r\n");
      out.write("							<label><input type=\"checkbox\" name=\"saveId\" ");
      out.print(saveId.length() == 0 ? "":"checked");
      out.write(" /> 아이디 저장</label>\r\n");
      out.write("							<input type=\"button\" value=\"회원가입\" onclick=\"location.href='");
      out.print(path);
      out.write("/member/enroll';\"/>\r\n");
      out.write("						</td>				\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("			</form>\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("		");
} else { 
      out.write("\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("				<table>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td colspan =\"2\">\r\n");
      out.write("							");
      out.print(loginMember.getName() );
      out.write("님 안녕하세요?\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td><button onclick=\"location.href='");
      out.print(path);
      out.write("/member/view';\">내정보</button></td>\r\n");
      out.write("						<td><button onclick=\"location.href='");
      out.print(path);
      out.write("/logout';\">로그아웃</button></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("		");
} 
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<nav>\r\n");
      out.write("		<ul class=\"main-nav\">\r\n");
      out.write("			<li class=\"home\"><a href=\"");
      out.print(path);
      out.write("\">Home</a></li>		\r\n");
      out.write("			<li class=\"notice\"><a>공지사항</a></li>		\r\n");
      out.write("			<li class=\"board\"><a href=\"");
      out.print(path);
      out.write("/board/list\">게시판</a></li>		\r\n");
      out.write("			");
 if(loginMember != null && loginMember.getRole().equals("ROLE_ADMIN")){
      out.write("\r\n");
      out.write("				<li class=\"admin-member\"><a href=\"");
      out.print(path);
      out.write("/admin/member\">회원관리</a></li>		\r\n");
      out.write("			");
} 
      out.write("\r\n");
      out.write("		</ul>\r\n");
      out.write("	</nav>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	List<Board> list = (List<Board>)request.getAttribute("list");
	PageInfo pageInfo = (PageInfo)request.getAttribute("pageInfo");
	
	String searchType = "title";
	String searchValue = ""; 
	String searchParamValue = request.getParameter("searchValue");
	if(searchParamValue != null && searchParamValue.length() > 0){
		searchType = request.getParameter("searchType");
		searchValue = request.getParameter("searchValue");
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("	section#board-list-container{width:600px; margin:0 auto; text-align:center;}\r\n");
      out.write("	section#board-list-container h2{margin:10px 0;}\r\n");
      out.write("	table#tbl-board{width:100%; margin:0 auto; border:1px solid black; border-collapse:collapse; clear:both; }\r\n");
      out.write("	table#tbl-board th, table#tbl-board td {border:1px solid; padding: 5px 0; text-align:center;} \r\n");
      out.write("	/*글쓰기버튼*/\r\n");
      out.write("	input#btn-add{float:right; margin: 0 0 15px;}\r\n");
      out.write("	/*페이지바*/\r\n");
      out.write("	div#pageBar{margin-top:10px; text-align:center; background-color:rgba(0, 188, 212, 0.3);}\r\n");
      out.write("	\r\n");
      out.write("	.input_text{width: calc( 60% - 14px); margin: 6px 7px; height: 30px; text-align:center;\r\n");
      out.write("           		  border: 0; font-weight: bold; font-size: 16px; outline: none;}\r\n");
      out.write("    .sch_smit{width: 54px; height: 40px; margin: 0; border: 0; \r\n");
      out.write("        		background: #007dd1; color: white; font-weight: bold; border-radius: 1px; cursor: pointer;}\r\n");
      out.write("    .sch_smit:hover{background: #007daa;}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<section id=\"content\">\r\n");
      out.write("	<h2 align=\"center\">자유 게시판</h2>\r\n");
      out.write("\r\n");
      out.write("	<form action=\"");
      out.print(path);
      out.write("/board/list\" method=\"get\">\r\n");
      out.write("		<div style=\"text-align: center;\">\r\n");
      out.write("			<label><input type=\"radio\" name=\"searchType\" value=\"title\" ");
      out.print(searchType.equals("title") ? "checked":"" );
      out.write(" />제목</label>\r\n");
      out.write("			<label><input type=\"radio\" name=\"searchType\" value=\"content\" ");
      out.print(searchType.equals("content") ? "checked":"" );
      out.write(" />내용</label>\r\n");
      out.write("			<label><input type=\"radio\" name=\"searchType\" value=\"writer\" ");
      out.print(searchType.equals("writer") ? "checked":"" );
      out.write(" />작성자</label>\r\n");
      out.write("			<br>\r\n");
      out.write("			<span class=\"blue_window\">\r\n");
      out.write("                <input id=\"searchValue\" name=\"searchValue\" type=\"text\" class=\"input_text\" value=\"");
      out.print(searchValue);
      out.write("\" />\r\n");
      out.write("              	<button type=\"submit\" class=\"sch_smit\">검색</button>\r\n");
      out.write("            </span>\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	");
if(loginMember != null) {
      out.write("\r\n");
      out.write("		<div style=\"text-align: right; margin-top: -40px;\">\r\n");
      out.write("			<button id=\"btn-add\" onclick=\"location.href='");
      out.print(path);
      out.write("/board/write';\">글쓰기</button>\r\n");
      out.write("		</div>\r\n");
      out.write("	");
} 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<table id=\"tbl-board\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th>번호</th>\r\n");
      out.write("			<th>제목</th>\r\n");
      out.write("			<th>작성자</th>\r\n");
      out.write("			<th>작성일</th>\r\n");
      out.write("			<th>첨부파일</th>\r\n");
      out.write("			<th>조회수</th>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		");
if(list == null || list.isEmpty()){  
      out.write("\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td colspan=\"6\">\r\n");
      out.write("					조회된 게시글이 없습니다.\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		");
} else { 
      out.write("\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("			");
for(Board b : list){ 
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>");
      out.print(b.getNo());
      out.write("</td>				\r\n");
      out.write("					<td><a href=\"");
      out.print(path+"/board/view?boardNo="+b.getNo());
      out.write('"');
      out.write('>');
      out.print(b.getTitle());
      out.write("</a></td>				\r\n");
      out.write("					<td>");
      out.print(b.getWriter_id());
      out.write("</td>				\r\n");
      out.write("					<td>");
      out.print(b.getCreate_date());
      out.write("</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						");
 if(b.getOriginal_filename() != null){ 
      out.write("\r\n");
      out.write("							");
      out.write("\r\n");
      out.write("							<img src=\"");
      out.print(path);
      out.write("/resources/images/file.png\" width=\"20\" height=\"20\"/>\r\n");
      out.write("						");
} else {
      out.write("\r\n");
      out.write("							<span>-</span>\r\n");
      out.write("						");
} 
      out.write("\r\n");
      out.write("					</td>\r\n");
      out.write("					<td>");
      out.print(b.getReadcount());
      out.write("</td>				\r\n");
      out.write("				</tr>\r\n");
      out.write("			");
} 
      out.write("\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		");
} 
      out.write("\r\n");
      out.write("	</table>\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<div id=\"pageBar\">\r\n");
      out.write("		");
      out.write("													\r\n");
      out.write("		<button onclick=\"movePage('");
      out.print(path);
      out.write("/board/list?page=");
      out.print(pageInfo.getStartPage());
      out.write("');\">&lt;&lt;</button>\r\n");
      out.write("		");
      out.write("	\r\n");
      out.write("		<button onclick=\"movePage('");
      out.print(path);
      out.write("/board/list?page=");
      out.print(pageInfo.getPrvePage());
      out.write("');\">&lt;</button>\r\n");
      out.write("\r\n");
      out.write("		<!-- 10개 목록 출력하기 -->\r\n");
      out.write("		");
 for(int i = pageInfo.getStartPage(); i <= pageInfo.getEndPage(); i++){ 
      out.write("\r\n");
      out.write("			");
if(i == pageInfo.getCurrentPage()){ 
      out.write("\r\n");
      out.write("				<button disabled>");
      out.print(i);
      out.write("</button>\r\n");
      out.write("			");
} else {
      out.write("\r\n");
      out.write("				<button onclick=\"movePage('");
      out.print(path);
      out.write("/board/list?page=");
      out.print(i);
      out.write("');\">");
      out.print(i);
      out.write("</button>\r\n");
      out.write("			");
} 
      out.write("\r\n");
      out.write("		");
} 
      out.write("\r\n");
      out.write("		");
      out.write("	\r\n");
      out.write("		<button onclick=\"movePage('");
      out.print(path);
      out.write("/board/list?page=");
      out.print(pageInfo.getNextPage());
      out.write("');\">&gt;</button>\r\n");
      out.write("		\r\n");
      out.write("		");
      out.write("													\r\n");
      out.write("		<button onclick=\"movePage('");
      out.print(path);
      out.write("/board/list?page=");
      out.print(pageInfo.getEndPage());
      out.write("');\">&gt;&gt;</button>\r\n");
      out.write("	</div>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function movePage(pageUrl){\r\n");
      out.write("		var searchValue = document.getElementById(\"searchValue\"); // 갤럭시\r\n");
      out.write("		var searchTypes = document.getElementsByName(\"searchType\"); // title\r\n");
      out.write("		var searchType = 'title';\r\n");
      out.write("		if(searchValue.value.length > 0){\r\n");
      out.write("			for(var i = 0; i <searchTypes.length; i++){\r\n");
      out.write("				if(searchTypes[i].checked == true){\r\n");
      out.write("					searchType = searchTypes[i].value;\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("			pageUrl = pageUrl + '&searchType=' + searchType + '&searchValue=' + searchValue.value; \r\n");
      out.write("		}\r\n");
      out.write("		location.href = encodeURI(pageUrl);	\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<footer>\r\n");
      out.write("		<p>\r\n");
      out.write("			&lt;Copyright 2022. <strong>KH정보교육원</strong>.All rights reserved. &gt;\r\n");
      out.write("		</p>\r\n");
      out.write("	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
